local_backend: true
backend:
  name: git-gateway
  branch: master
media_folder: 'src/uploads'
public_folder: '/uploads'

navigation: &NAVIGATION
  label: 'Navigation'
  name: 'eleventyNavigation'
  widget: 'object'
  collasped: true
  fields:
    - { label: 'Key', name: 'key', widget: 'string', required: false }
    - { label: 'Parent', name: 'parent', widget: 'string', required: false }
    - { label: 'Order', name: 'order', widget: 'number', required: false }
    - { label: 'Excerpt', name: 'excerpt', widget: 'string', required: false }

meta: &META
  label: 'Meta'
  name: 'meta'
  widget: 'object'
  collapsed: true
  fields:
    - { label: 'Title', name: 'title', widget: 'string', required: false }
    - { label: 'Description', name: 'desc', widget: 'string', required: false }
    - { label: 'Social Image', name: 'socialImage', widget: 'image', required: false }

button: &BUTTON
  label: 'Button'
  name: 'button'
  widget: 'object'
  collapsed: true
  fields:
    - { label: 'Text', name: 'text', widget: 'string', required: false }
    - { label: 'Link', name: 'link', widget: 'string', required: false }

themeOptions: &THEMEOPTIONS
  - { label: 'Red', value: 'bg-primary' }
  - { label: 'Green', value: 'bg-secondary' }

theme: &THEME
  label: 'Theme'
  name: 'theme'
  widget: 'select'
  collapsed: true
  required: false
  options:
    - { label: 'Red', value: 'bg-primary color-light' }
    - { label: 'Green', value: 'bg-secondary color-light' }
    - { label: 'Bagle', value: 'bg-bagle color-dark' }
    - { label: 'Gold', value: 'bg-secondary color-gold' }
    - { label: 'Attention', value: 'bg-secondary color-attention' }

blocks: &BLOCKS
  label: 'Blocks'
  name: 'blocks'
  widget: 'list'
  types:
    - label: 'Text'
      name: 'text'
      widget: object
      fields:
        - { label: 'Content', name: 'content', widget: 'markdown' }
        - { label: 'Spacing Top', name: 'spacingtop', widget: 'string', required: false }
        - { label: 'Spacing Bottom', name: 'spacingbottom', widget: 'string', required: false }
    - label: 'Image'
      name: 'image'
      widget: 'object'
      fields:
        - { label: 'Image', name: 'image', widget: 'image' }
        - { label: 'Alt', name: 'alt', widget: 'string', required: false }

collections:
  - label: 'Pages'
    name: 'pages'
    folder: 'src'
    identifier_field: 'title'
    create: true
    filter: {field: "type", value: "page"} # I think i can use this to control what is seen in the CMS for the page listing
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
    nested:
      depth: 100 # max depth to show in the collection tree
      summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field
    extension: 'md'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'layouts/page.njk' }
      - { label: 'Page type', name: 'type', widget: 'hidden', default: 'page' } #set a custom field of type equal to page - we then use a filter above to only list the pages where the type is set to 'page'
      - { label: 'Title', name: 'title', widget: 'string' }
      - *BLOCKS
      - *META
      - *NAVIGATION
  # - label: "Globals"
  #   name: "globals"
  #   files:
  #     - label: "FAQs"
  #       name: "faqs"
  #       file: "src/_data/faqs.json"
  #       fields:
  #         - label: Items
  #           name: items
  #           widget: list
  #           fields:
  #             - { label: 'Summary', name: 'summary', widget: 'string' }
  #             - { label: 'Detail', name: 'detail', widget: 'markdown' }
